apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-nats-data-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-nats-data-ingest
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-nats-data-ingest
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: sftp-key
        secret:
          secretName: dq-nats-data-ingest
          items:
          - key: SSH_PRIVATE_KEY
            path: id_rsa
            mode: 400
      - name: nats-volume
        persistentVolumeClaim:
          claimName: nats-volume
      containers:

      - name: dq-nats-data-ingest
        image: quay.io/ukhomeofficedigital/dq-nats-sftp-python:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: {{.NATS_CPU_LIMIT}}
            memory: {{.NATS_RAM_LIMIT}}
          requests:
            cpu: {{.NATS_CPU_REQUEST}}
            memory: {{.NATS_RAM_REQUEST}}
        env:
          - name: SSH_REMOTE_HOST
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: SSH_REMOTE_HOST
          - name: SSH_REMOTE_USER
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: SSH_REMOTE_USER
          - name: SSH_PRIVATE_KEY_PATH
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: SSH_PRIVATE_KEY_PATH
          - name: SSH_LANDING_DIR
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: SSH_LANDING_DIR
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: S3_BUCKET_NAME
          - name: S3_KEY_PREFIX
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: S3_KEY_PREFIX
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: S3_SECRET_ACCESS_KEY
          - name: GA_S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: GA_S3_BUCKET_NAME
          - name: GA_S3_KEY_PREFIX
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: GA_S3_KEY_PREFIX
          - name: GA_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: GA_S3_ACCESS_KEY_ID
          - name: GA_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: GA_S3_SECRET_ACCESS_KEY
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: dq-nats-data-ingest
                key: SLACK_WEBHOOK
          - name: CLAMAV_URL
            value: "dq-clamav"
          - name: CLAMAV_PORT
            value: "443"
        volumeMounts:
        - name: sftp-key
          mountPath: /key
          readOnly: true
        - name: nats-volume
          mountPath: /NATS
